PMPHA~ATL]VWtEHAvABHAGPMKJ.@AWGVMTPMKJe@EJGAKBWLE@KSWQJ@AVEWMHAJPWO]
iQGLHMOA~KVFEWSMH@LAEVPBMJ@MJCTAEGAMJVABHAGPMKJ
mJBHQAJGA@F]|||pajpegmkjWP]HA
.TVKITPhK	BMLMT	LKTPVEGO|||pajpegmkjWP]HASMPLIAHEJGLKHMGEGKQWPMGCQMPEVIAHK@]@AATVAWKJEJPWLE^]EPIKWTLAVMGTE@WIQPA@PVET@VQIWKGGEWMKJEHAPLAVAEHRKGEHWEITHAWSEVIEJEHKCW]JPLPA\PQVAWMJPVKWTAGPMRAEJ@WKIFAVIKK@BAEPQVMJCEWKBPRQHJAVEFHAIEHARKGEHSMPLWQFPHAEQPK	PQJAEJ@E@	HMFW
.GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAEPPSMHMCLPFEPLA@MJEWKBPTEHAFHQAIKKJCHKSSMPLJAKJVABHAGPMKJWKJSAPWPVAAPW
eHKJAGHKEOA@BMCQVAWPEJ@WKJEWO]WGVETAVWA@CAHKKOMJCKQP
wGM	BMAHAIAJPWHMOALKHKCVETLMGTVKNAGPMKJWEJ@WQFPHAAJAVC]WPVAEOWMJPLAWO]
fHAJ@MJCWQVVAEHMWIEJ@GKJPAITKVEV]@MCMPEHEVPRMWQEHH]WPVMOMJC
.WB\`MWPEJPGMP]LQIWQFPHASMJ@GLMIAWWKBPVEMJBEHHMJCW]JPLAWM^A@APLAVAEHSLMWTAVWCHMPGL]WPEPMGFQVWPWIQBBHA@LAEVPFAEPW
.RKGEHWwKBPIEHARKGEHIAHEJGLKHMGEJ@MJPVKWTAGPMRASMPLEWHMCLPEQPK	PQJAABBAGP
.RKGEHWwPVQGPQVA@hK	BMLMT	LKTPVEGOSMPLEWIKKPLEPIKWTLAVMGMJPVKCAJPHARAVWAWFQMH@MJCMJPKEVABHAGPMRAGLKVQWMJWPVQIAJPEHFVAEOWSMPLHE]AVA@TE@WEJ@EBE@MJCMJPVKWTAGPMRAKQPVKBAEPQVMJCERQHJAVEFHAA\TVAWWMRAIEHARKGEH
.OA]SKV@WHKBMLMTLKTAIKLKTPVETEHPAVJEPMRAvfWE@VETGHKQ@VETEIFMAJPLMTLKTIAHEJGLKHMGMJPVKWTAGPMRAEPIKWTLAVMGGMJAIEPMGWKQJ@PVEGO|||pajpegmkjWP]HAIKKJHMCLPRMFAWVABHAGPMKJ.GK@AjEIA~KVFEPLAcVAAO.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]|||pajpegmkj	ikkjhmclp
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV~.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
