PMPHArMFVEJP`ESJaGLKAW.@AWGVMTPMKJmJPLAUQMAPKBIKVJMJCJEPQVAWW]ITLKJ]QJBKH@W
mJWTMVA@F]PLAWP]HAKBuqemhwkqj`l`PLMWPVEGOGETPQVAWPLAPVEJUQMHESEOAJMJCKBEJAS@E]
.TVKITPeIFMAJPWKQJ@WGETASMPLCAJPHAFMV@GEHHWWKKPLMJCJEPQVEHRMFAWWAVAJAIAHK@MAWHE]AVA@EPIKWTLAVMGPA\PQVAWGEHIMJCBHQPAJEPQVA	MJWTMVA@W]JPLWPVEJUQMHEJ@IA@MPEPMRA
bAIEHARKGEHSLMWTAV]EJ@APLAVAEH
.GKRAVeVPtVKITPeWAVAJA@ESJHEJ@WGETASMPLWKBPAPLAVAEHHMCLPBMHPAVMJCPLVKQCLIMWP]PVAAWPVEJUQMHEJ@@VAEIHMOA
fMV@WMJBHMCLPCAJPHATEWPAHGKHKVWEJ@ETAEGABQHLEVIKJMKQWEPIKWTLAVA
.WB\WKBPFMV@GLMVTWCAJPHAVQWPHMJCHAERAW@MWPEJPSEPAVPVMGOHAWKBPSMJ@GLMIAW.RKGEHWBAIEHARKGEHCAJPHASLMWTAVWAPLAVAEHEJ@EMV].RKGEHWwPVQGPQVA@EIFMAJPPVEGOSMPLEWAVAJAMJPVKEJ@WKKPLMJCKQPVKBAEPQVMJCSLMWTAV]BAIEHARKGEH.OA]SKV@WEIFMAJPJEPQVAWKQJ@WGETAPVEJUQMHIA@MPEPMRAVAHE\EPMKJAPLAVAEHGEHIWKKPLMJCFMV@WKJC.GK@AjEIArEJMP]bEMV.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]uqemhwkqj`l`	fEPEMViKVJMJCUQEMHrKHQIAwQFELOMESE^
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVr.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	`ESJeSEOAJMJCy.KKKKKMMMMMM..RAVWA	jEPQVAWfVAEPLy.CAJPHASLMWTAVW.WKBPAGLKAW.PLASKVH@ESEOAJW.MJUQMAPLEVIKJ]..GLKVQW	iKVJMJChMCLPy.KKKKK.MMMMMMMM..FVM@CA	wAVAJAaGLKAWy.FVAA^ASLMWTAVW.HAERAW@EJGA.QJ@AVPLAVMWMJCWQJ..KQPVK	tAEGABQHvATVMWAy.KKKKKK.MMMMMMM..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
