PMPHAjAKJfEGOVKE@.@AWGVMTPMKJeVKE@WPVAPGLMJCPLVKQCLIAIKV]EJ@HMCLP∆§∞SLAVAKH@@VAEIWIAAPJASJAKJWOMAW
.TVKITPgKQJPV]TKTFHAJ@SMPLIK@AVJTVK@QGPMKJEGKQWPMGCQMPEVTMGOMJCQJ@AVWIKKPLTAVGQWWMKJSEVIWHM@ACQMPEVEGGAJPWWKBPTMEJKFEGO@VKTWPAE@]IM@	PAITKCVKKRASMPLFVMCLPIAHK@MGLKKOWAIKPMKJEHIEHARKGEHLAEVPBAHPPKJA.GKRAVeVPtVKITPJMCLPPMIA@AWAVPLMCLSE]CHKSMJCSMPLLKHKCVETLMGJAKJWMCJWTMGOQTPVQGOWMHLKQAPPAQJ@AVRMKHAPWO]WKBPLE^AGMJAIEPMGHMCLPMJCBQPQVMWPMG]APVQWPMGPKJA.WB\SMJ@FHKSMJCPLVKQCLPEHHCVEWWPVQGOAJCMJALQIBEMJPGMP]AGLKEIFMAJPJMCLPMJWAGPW.RKGEHWIEHARKGEHSEVIPMIFVAPAJ@AV]APGKJBM@AJPPKJA.RKGEHWwPVQGPQVA@IK@AVJGKQJPV]TKTWPATPVEGOWPAE@]FQMH@SMPLWPKV]PAHHMJCRAVWAW@]JEIMGHE]AVA@GLKVQWAWEJ@WIKKPLKQPVKBAEPQVMJCAIKPMKJEHIEHARKGEH.OA]SKV@WGKQJPV]TKTEIAVMGEJEBKHOTKTWKQPLAVJVKGOLAEVPHEJ@EGKQWPMGWPKV]PAHHMJCAIKPMKJEHWKQJ@PVEGOIKVCEJSEHHAJWP]HAGMJAIEPMGIM@PAITKJAKJRMFA.GK@AjEIAjKVPLEJCAVeFFA].FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]iKVCEJsEHHAJ	iKVCEJsEHHAJ	wIMHAkBBMGMEHiQWMGrM@AK
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVj.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR

	OIT.@QVEPMKJ..H]VMGWMJWPy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
