C^C[R
vD_RDXQxBEgEXZ^DR=SRDTE^GC^XY
c_RTXYQRDD^XYYRAREDGX\RYURTXZRDV_VBYC^YPQ^R[SXQ[^P_C~YC_RDCN[RXQzX_DRYt_VAXD_^Õ·£VGB[DRURC@RRY[XYP^YPVYSSRDC^YN=GEXZGC
eXZVYC^TGXGUV[[VSRZXC^XYV[G^VYXVYSDXQCDCE^YPDU[RYS^YP@^C_DBUC[RR[RTCEXY^TCROCBERD_RVECCBPP^YPZR[XS^RDT^YRZVC^TSRGC_VZU^RYCVCZXDG_RERZV[RAXTV[E^T_VYSEVDGN@^C_RZXC^XYV[YBVYTR=TXAREvECgEXZGC
c@XP[X@^YPQ^PBERDZRRCBYSREVQEVTCV[VBEXEVC_R^ED^[_XBRCCRDDBEEXBYSRSUNS^DDX[A^YPGRCV[DXQ[^P_CQBCBE^DC^TT^CND\N[^YRU[BEERS^YC_RUVT\PEXBYSSERVZNYRXYGV[RCCRDXQC[BZ^YRDTRYC_VMR=DQO
PRYC[RUERVC_DXBYSDEV^YCVGG^YPP[VDDERAREUSERYT_RSVZU^RYCYX^DRQV^YCA^YN[TEVT\[RSBE^YPCEVYD^C^XYD=AXTV[D
ZV[RAXTV[RZXC^XYV[SR[^ARENSRRGCXYR^YC^ZVCRVYSDXB[QB[=AXTV[DdCEBTCBERS
GXGDCRGCEVT\@^C_PXXS^YCEXVYSY^TRXBCEX^YT[BS^YPDXZRSEXGD@^C_ZR[XS^TZV[RAXTV[VYSRZXC^XYV[G_EVD^YP=\RN@XESD
GXGEXZVYC^TDXB[UV[[VSGRED^VYDCN[RT^YRZVC^TDXBYSCEVT\RZXC^XYV[ZXXSNZX_DRYT_VAXD_^DCN[R[XARSVE\EXZVYTR=TXSRyVZR
vCXYRZRYC=UGZ
=PRYER~YGBC
GXG=GEXZGC~YGBC
VEXZVYC^TGXRZ@^C_aXTV[[^\RzX_DRYt_VAXD_^=[RCCRE
v=^YT[BSRaXTV[
qV[DR=VGGaRED^XY
A\ZG=SBEVC^XY
==[NE^TD
l^YCEXQVSRS_RVECURVCj=XXXXXXXVVVVVV_=DNYC_@_^DGRE`_RY@XESDQXEPRCC_R^ED_VGRD==lAREDRd^[RYC`XBYSj=c_RZXXYERDCDXYNXBEYVZR=~CXBT_C_RRT_XVYS^CUBEYD=`R@RERZVSRXQGEXZ^DRD=`E^CCRYXYZR[C^YPP[VDD==lGERT_XEBDpEVA^CNgB[DRj=V_____^^^^XXX_=nXBVERC_RD^[RYTR~ERZRZURE=c_RD^[RYTR~DC^[[URTXZR==lT_XEBDqV[[^YPaREDRj=vD_RDXQXBEGEXZ^DR=cBEYCX[^P_C@^C_^YZNT_RDC=sXYÕ·®CTV[[^C[XAR=tV[[^CC_RD[X@BYSX^YPXQDCVED==lUE^SPReRAREUuERV\j=^^^^^^VVVVVV=xBEP_XDCDSVYTRD[X@=BYSRE^YA^D^U[REV^Y==lXBCEXd[X@s^DDX[ARj=DNYC_UERVC_~QXEP^ARC_RS^DCVYTR=UBCYXCC_RSERVZ=XXXXXX==tERVCRSUNvcg[VNRE=_CCGD@@@VCG[VNRETXZ==tXGNE^P_Cõžv\C^D~YT