PMPHAwKQHBQHnKQVJA].@AWGVMTPMKJeNKQVJA]KBPLAWKQHPVEGMJCTEPLWPLVKQCLPMIAEJ@WTEGABMJ@MJCTAEGAMJPLAUQMAPIKIAJPW
mJWTMVA@F]PLAWAVAJAEJ@LAEVPBAHPWP]HAKBPLAPVEGOlQIWEBEV
.TVKITPaIKPMKJEHEGKQWPMGCQMPEVCAJPHATMEJKIAHK@MAWWAVAJAWPVMJCWWKKPLMJCVL]PLISEVIFEWWHMJALAEVPBAHP@QAPIEHAEJ@BAIEHARKGEHWPAJ@AVEJ@A\TVAWWMRA.GKRAVeVPtVKITPeWAVAJAHEJ@WGETAEPPSMHMCLPSMPLEVMRAVVABHAGPMJCPLAWPEVWAPLAVAEHCHKSGEHIMJCEJ@PVEJUQMHIK@AVJEVPMWPMGWP]HASMPLWKBPTEWPAHGKHKVW.WB\CAJPHAVMRAVBHKSWQFPHAVQWPHMJCHAERAW@MWPEJPFMV@GEHHWWKBPSLMWTAVWKBPLASMJ@.RKGEHWIEHAEJ@BAIEHA@QAPPAJ@AVEJ@LEVIKJMKQWFHAJ@MJCWKBPH]CAJPHAAGLKAW.RKGEHWwPVQGPQVA@EGKQWPMGTKTPVEGOWIKKPLMJPVKEJ@GEHIMJCKQPVKSMPLLEVIKJMKQW@QAPRKGEHWEJ@CAJPHAMJWPVQIAJPEHFVAEOW.OA]SKV@WEGKQWPMGTKTMJ@MABKHOGLMHHWAVAJA@QAPWKQHBQHLAEVPBAHPGEHIMJCGMJAIEPMGWKQJ@PVEGOTAEGABQH}vblQIWEBEV.GK@AjEIAwM@@LEVPLE.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]}vb	lQIWEBEVwKJCXwEM]EEVEXeLEEJtEJ@E]XeJAAPtE@@EXwEGLAPtEVEITEVEpEJ@KJmVWLE@oEIMH
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVw.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
