LQLT]~TYU]KW^~WJZQ\\]Vt]KKWVK2\]K[JQHLQWVqVYOWJT\W^^WJZQ\\]VSVWOT]\_]OP]J]^TYU]K\YV[]OQLP\]KQJ]YT]KKWVMV^WT\KQVLP]KPY\WOKqVKHQJ]\ZALP]KLAT]W^YV]T][LJWVQ[\J]YU2HJWUHL}V]J_]LQ[]T][LJWVQ[Z]YL\]]HKAVLPKHMTKQV_ZYKKUAKL]JQWMKU]TW\Q]KYLUWKHP]JQ[HY\KKMTLJA^]UYT]NW[YT]VQ_UYLQ[YV\ZWT\UWW\2[WN]JyJLhJWUHLy^MLMJQKLQ[[TYKKJWWUOQLPV]WVTQ_PLKYPWTW_JYHPQ[L]Y[P]JYV\YKMJJ]YT\J]YUTQS]YLUWKHP]J]uW\]JVNQZJYVL[WTWJKOQLPYPQVLW^UAKL]JAYV\YTTMJ]2K^@OPQKH]JQV_OQV\KKMZLT][TYKKJWWU][PW]KKW^L]T][LJWVQ[[PQU]K^YQVLP]YJLZ]YLK2NW[YTK^]UYT]NW[YTKMTLJAYV\UAKL]JQWMKTYA]J]\PYJUWVQ]K\Q_QLYT][PW]K2NW[YTKkLJM[LMJ]\]T][LJWVQ[HWHLJY[SOQLPYV]V_Y_QV_QVLJWYV\Y[YHLQNYLQV_WMLJW^]YLMJQV_YKMTLJA^]UYT]NW[YT2S]AOWJ\K]T][LJWHWHKAVLPOYN]\YJSHWH[QV]UYLQ[KWMV\LJY[SUAKL]JQWMKKMTLJA^MLMJQKLQ[\J]YUTQS]]VQ_UYLQ[2[W\]vYU]~YPJ]VP]QL	2ZHU	

2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZAzTY[SHWWTl]Y[P]JSQKKQV_PWLKLM\]VLmK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]J~2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN

		2\MJYLQWV



22TAJQ[K22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PLú‘

ySLQKqV[