LQLT]rY\]\}[PW]K]UYu]UM\YJ2\]K[JQHLQWVoPQKH]JKW^LP]HYKL][PWQVV]WVJ]^T][LQWVKY\YV[]W^KPY\WOKYV\TQ_PLQVY[QLALPYLV]N]JKT]]HKqVKHQJ]\ZALP]KLAT]W^|]]HWV_YVWKLYT_Q[A]LUW\]JVRWMJV]A2HJWUHL}V]J_]LQ[|rZJ]YSZ]YLKTWOJPALPUQ[ZMQT\[YHLQNYLQV_H]J[MKKQWV\]]HZYKKJ]KWVYV[]YLUWKHP]JQ[KAVLPKVWKLYT_Q[A]LUW\]JVNQZ]^]UYT]NW[YTOPQKH]JALWV]2[WN]JyJLhJWUHLv]WVTQLMJZYVTYV\K[YH]^MLMJQKLQ[[QLAKSATQV]YL\MKS_TWOQV_J]^T][LQWVKWVO]LKLJ]]LKUW\]JVYV\KT]]S\]KQ_VNQZJYVL[WTWJKOQLPYLWM[PW^UAKL]JA\AVYUQ[YV\]V_Y_QV_NQKMYTK2K^@[QLAYUZQYV[]][PWQV_^WWLKL]HKKW^LOPQKH]JK\QKLYVLLJY^^Q[PMUJPALPUQ[[TYHK2NW[YTK^]UYT]NW[YTOPQKH]JAYV\]LP]J]YTTYA]J]\PYJUWVQ]KKUWWLPLJYVKQLQWVK2NW[YTKkLJM[LMJ]\ZJ]YSZ]YLLJY[SOQLPY[YHLQNYLQV_QVLJWYV\KUWWLPWMLJWQV[TM\QV_YLUWKHP]JQ[\JWHKOQLP]V[PYVLQV_^]UYT]NW[YT2S]AOWJ\KZJ]YSZ]YL\R]T][LJWVQ[YUZQ]VLVWKLYT_Q[^MLMJQKLQ[[QV]UYLQ[KWMV\LJY[SMJZYV\]]HWV_V]WVNQZ]KUAKLQ[YTYLUWKHP]JQ[\YV[]UW\]JV2[W\]vYU]rYV]}AJ]2ZHU	
2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZA|]]HWV_lqslwsuytyakqyktwol}jzyjm

D|rzj}ysz}ylzqty{qvly|q|mklymK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]Jr2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN

		2\MJYLQWV

22TAJQ[KcQVLJWYUZQYV[]e22cOPQKH]J]\N]JK]e22cKAVLP\JWHe22cOPQKH]J]\N]JK]e22cKW^L[PWJMKe2WWWWWW22cWMLJWe22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PLú‘

ySLQKqV[