PMPHAvAWKJEJGAKBPLAmJBMJMPAvAWKJEJGME@AHmJBMJMPK.@AWGVMTPMKJeNKQVJA]PLVKQCLPLAIMJ@WHEF]VMJPLSLAVAARAV]WPATMWEJKPAMJEJAJ@HAWWIAHK@]
mJWTMVA@F]PLAWP]HAKB`pk
.TVKITPeIFMAJPWKQJ@WGETAAPLAVAEHW]JPLWI]WPMGEHEPIKWTLAVA@AATIA@MPEPMRAPKJAWWKKPLMJCTE@WPVEJUQMHVL]PLIWTMVMPQEHEJ@GEHIMJCIEHAEJ@BAIEHARKGEHSLMWTAVW.GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAEP@ESJWLMIIAVMJCHMCLPWAPLAVAEHCHKSI]WPMGEHEIFMEJGAIK@AVJEJ@GETPMREPMJCWAVAJA]APRMFVEJPGKHKVW.WB\CAJPHASMJ@GLMIAWWKBPSEPAVWPVAEIW@MWPEJPFMV@GEHHWWQFPHAAHAGPVKJMGTQHWAW.RKGEHWIEHAEJ@BAIEHASLMWTAVWAPLAVAEHGLEJPMJCWAVAJAEJ@GEHIMJCLEVIKJMAW.RKGEHWwPVQGPQVA@EIFMAJPPVEGOCAJPHAMJPVKEJ@WIKKPLKQPVKSMPLAPLAVAEHRKGEHSLMWTAVWEJ@IAHK@MGGLEJPW.OA]SKV@WEIFMAJPGLMHHKQPIA@MPEPMRAAPLAVAEH@KSJPAITKWTMVMPQEHWKQJ@PVEGOVAHE\MJC`pkI]WPMGEHPVEJUQMHWAVAJABQPQVMWPMGRMFAWGEHIMJC.GK@AjEIAvE]QAHE.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]`pk	lEVlEVAlEVM
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVv.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKSLMWTAVWy..FVAA^AWKQJ@y..GEHIRAVWAy..KKKKK..IA@MPEPMRAGLKVQWy..ELLLLL..KQPVKSLMWTAVWy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
