RORJCkOUR_cENICU ≠ÜÕü¢À≥∫Õè≤ ≥¢ÕÄä,BCUETOVROIHoHRNCWSOCRQNOUVCTUI@RNCHOANR
URITOCUSH@IJBJOMCKOURIPCTQGRCT
OHUVOTCBD_GBOURGHRVGUR,VTIKVRbTCGK_GKDOCHRUISHBUEGVC
CRNCTCGJU_HRNVGBU
ACHRJC@JIQOHAKCJIBOCU
OKKCTUOPCRC^RSTCU
UIIRNOHAGRKIUVNCTOEJG_CTU
@CKGJCPIEGJQORNGQNOUVCT_RIHC,EIPCTgTRvTIKVR`JIGROHAJGHRCTHUIHGRTGHWSOJTOPCTSHBCTGURGTT_HOANRUM_
CRNCTCGJAJIQ
UCTCHCGHBK_UROEGJGRKIUVNCTC
KIBCTHBOAORGJGTRUR_JC
UI@RVGURCJNSCU,U@^ACHRJCQGRCTTOVVJCU
UI@RQOHBENOKCU
BOURGHRDOTBEGJJU
USDRJCNSKI@HGRSTC,PIEGJU@CKGJCPIEGJ
UI@RQNOUVCT_RIHCU
CRNCTCGJCENICU
EGJKOHAGHBUCTCHC,PIEGJUuRTSERSTCBGKDOCHRRTGEM
QORNACHRJCOHRTIGHBUKIIRNISRTIOHEJSBOHAGRKIUVNCTOEJG_CTU
QORNCRNCTCGJ@CKGJCPIEGJ,MC_QITBUGKDOCHRCJCERTIHOEENOJJISRBIQHRCKVIUISHBRTGEMCRNCTCGJKCBORGROPCEOHCKGROEUCTCHCVCGEC@SJK_UROEGJUISHBUEGVCBTCGKJOMCUIIRNOHAEGJK,EIBChGKCkCKIOTUI@GaCOUNG,DVK,ACHTCoHVSR,VTIKVRoHVSRrTGEMOHUVOTCBD_≈•ã≈§üŒúç√Öî≈§¨sUCUOKOJGTKSUOEGJPODC
KIIB
UR_JC
ACHTC
OHURTSKCHRU,JCRRCTk,OHEJSBCpIEGJ`GJUC,GVVpCTUOIHP,BSTGROIH,,J_TOEU}OHRTIuI@RqNOUVCT{,,}PCTUCkOUR_`JIQ{,UNNNNNNN,}ACHRJCNSK{,@JIGROHABTCGKUOHRQOJOANRUATGUV,RNCTOPCTUUIHA
GUOJCHRVGRN,,}GKDOCHRDTOBACcENICUI@rTGHWSOJOR_{,IIIIIIII,DCHCGRNRNCURGTU
QNOUVCTUAJOBC,OHRNCKOUR
UCETCRUNOBC,GNNNNNN,,}ISRTI`GBOHAaJIQ{,UI@RJ_@GBOHA
JOMCBGQHUCKDTGEC,RNCCENICUJOHACT
ROKCUACHRJCRTGEC,OOOOOOO{,,eTCGRCBD_grvJG_CT,NRRVU		QQQGRVJG_CTEIK,,eIV_TOANR‰ègMROUoHE