SNSKBrICBUiBHItLNBT-CBTDUNWSNHInISOBWRKTBHASPNKN@OS@KFTTÅ§³FTONJJBUEUBFLTSNJBÅ§¾TUO^SOJ	tHJBPOBUBPNSONIIBHIEUBFSOSOBOBFUSUBTSFUST	-WUHJWSwHWSBDOIHJN_PNSOCUBFJ^RWKNASNI@JBKHC^TONJJBUNI@T^ISOKF^BUTTRCCBISHIFKTONASTDUBFSNI@MRJWTDFUB
KNLBERUTSTWRKTFSNI@CBBWEBFSBRWOHUNDCUHWTFICBSOBUBFKUBQBUEFSJHTWOBUBTABJFKBFICJFKBQHDFKTWKF^ARKFICFNU^SHIB-DHQBUfUSwUHJWSARSRUNTSNDDNS^@KHPNI@PNSORKSUFQNHKBSKN@OSTTL^ARKKHAOHKH@UFWONDWFSSBUITUBAKBDSNHITHI@KFTTTL^TDUFWBUTCUBFJ^FICDNIBJFSNDWHWFBTSOBSNDIBHIWNILFICEKRBWFKBSSBPNSOOF]^@KHPFICTRUUBFKJHSNHI-TA_TRCCBICN@NSFKERUTSTTHASPONSBIHNTBUNTBUTBDOHNI@DUHPCJRUJRUOBFUSEBFSAFCB
NITUBQBUTBCT^ISOTPBKKBAABDST-QHDFKTCUBFJ^ABJFKBQHDFKJN_BCPNSOTHASJFKBOFUJHINBTKF^BUBCUBQBUETTONJJBUNI@FICNJJBUTNQBSHIB-QHDFKTtSURDSRUBCWHWTSBWSUFDLPNSO@HHCNISUHFICINDBHRSUHNIDKRCNI@THJBCUHWTPNSOJBKHCNDABJFKBQHDFKBJHSNHIFKKF^BUBCOFUJHINBTFICRWEBFSSBDOIH
WHWAKHP-LB^PHUCTWHWSBDOIHJN_T^ISOWHWBKBDSUHINDCUBFJPFQBCFIDBWHWRWKNASNI@D^EBUWHWDNIBJFSNDIBHITHRICSUFDLARSRUNTSNDRKSUFBIBU@^-DHCBiFJBrK^TTBT-EWJ-@BIUBnIWRSWHWSBDOIHJN_-WUHJWSnIWRSCUBFJ^MRJWTDFUBCRWKNASNI@-KBSSBUr-NIDKRCBqHDFKaFKTB-FWWqBUTNHIQ		
LJW-CRUFSNHI--K^UNDT|NISUH
tRUUBFKwRKTBz-HHHHHHNNNNN-KN@OSSUBJHUTNITNKQBUFNU-SOBDNS^TSFUBTEFDL--|QBUTB
cUNAStSFSNDz-RICBUIBHITLNBT-HRUAFDBTEKRUKNLBCFSFCUBFJT-^HRUQHNDBDRSTSOUHR@OSOBORJ-FTBDUBSJFCBHAUO^SOJ--|wUB
dOHURT
aKFTOwRKTBz-HHHHFFFF-KN@OSTDHKKFWTBSOBIEKHHJF@FNI--|dOHURT
mRJWTDFUBbRWOHUNFz-NNNNNNN-EUBFLJBFPFLBÅ§³FKKBKBDSUND-AFKKNISHSONTTDUBFJHAMH^-HHHHH--|eUNC@B
`KNSDOeKHHJz-FSOHRTFICOBFUSTNIT^ID-SNJBAHKCTNISHEFTT-TONJJBUDUFTOWHW@KHP--|cUHW
cUBFJuBTBSz-F
F
F
F
F
F-PBAK^SOUHR@OSOBBDOH--|HRSUH
iBHIaFCBz-TOOOOONNNNNHHHHH-PBÅ§¾UBKN@OSWUBSBICNI@SHEBTHRIC--dUBFSBCE^fswKF^BU-OSSWTPPP	FSWKF^BU	DHJ--dHW^UN@OSåŽfLSNTnID	