PMPHAqJ@AVjAKJgQVVAJPW.@AWGVMTPMKJlASEJ@AVA@PLVKQCLWKQJ@SERAWMJWPAE@KBTECAWGLEWMJCVL]PLIMJWPAE@KBPVQPL
wKIASLAVAFAPSAAJFEWWEJ@TQHWALABKQJ@EJASk@]WWA]
.TVKITPaJAVCAPMGPAGLJK@EJGAVL]PLI@AATVKHHMJCFEWWBEWP	TEGA@TAVGQWWMKJhEPMJ	MJWTMVA@W]JPLWPEFWFKH@GHMIEPMG@VKTWHE]AVA@EVTACCMEPKVWBQPQVMWPMGGHQFIKK@IEHABAIEHARKGEHIM\CVMPP]EJ@THE]BQH.GKRAVeVPtVKITPcHKSMJCG]FAV@EJGABHKKVMJEBQPQVMWPMGGMP]@EJGAVWIE@AKBHMCLPIKRAEIKJCLKHKCVETLMGTEHIPVAAWTQHWMJCFAEPWWLETMJCPLAWO]HMJAJAKJVABHAGPMKJWEGVKWW@MCMPEHKGAEJSERAW.WB\VMWMJCW]JPLWSAATWVKFKPMGLEJ@GHETWHEWAVVARAVFWLKPWHKS	AJ@WQFTQHWAWEIFMAJPGVKS@IQVIQVWSMPL@MCMPEH@MWPKVPMKJ.RKGEHWIEHAEJ@BAIEHARKGEHIM\VL]PLIMGGLEJPWEJ@WLKVPWLKQPWAJAVCAPMG@AHMRAV]GKJBM@AJPEJ@HMRAH].RKGEHWwPVQGPQVA@PAGLJK@EJGAPVEGOSMPLWLEVTMJPVKEJ@WIKKPLKQPVKIQHPMTHAMJPAJWA@VKTWVL]PLIMGIEHAGLEJPEJ@THE]BQHBAIEHAVAWTKJWA.OA]SKV@WPAGLJK@EJGAA@ILKQWAHEPMJPAGLGHQFAHAGPVKJMGFEWW@NVKGOEBQPQVMWPMGRMFAWGMJAIEPMGWKQJ@PVEGOGHQFEJPLAIJAKJFAEP.GK@AjEIAqH]WWAW.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]`NvKGOE	femhehkvkgo}	`nvkgoermwqehm~av
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVq.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR

	OIT.@QVEPMKJ..H]VMGWMJWPy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
